- x: "Apple stock soars to record highs following AI-focused WWDC event"
  y: 0.07
- x: "Apple's stock declined on Monday after the WWDC event"
  y: -0.02
- x: "Apple stock price surges on dividend and stock buyback news despite weak iPhone sales"
  y: 0.07
- x: "Apple shares fell sharply in response to President Trump's plan to put steep tariffs on products made abroad"
  y: -0.09
- x: "Apple reports record profits"
  y: 0.10
- x: "Apple's Q4 earnings report triggers share price movement amid China performance concerns"
  y: -0.04
- x: "Apple unveils new iPhone model at annual launch event"
  y: 0.03
- x: "Apple's services revenue shows strong year-over-year growth"
  y: 0.02
- x: "Apple's stock saw a significant pullback after reaching a record high in mid-July"
  y: -0.17
- x: "Apple announces $110 billion stock buyback plan"
  y: 0.05
- x: "Apple's stock rallies significantly after August correction"
  y: 0.13
- x: "Apple stock hits new record high after Apple Intelligence reveals at WWDC 2024"
  y: 0.072
- x: "Apple shares fall moderately after first day of WWDC, rebound sharply next day"
  y: 0.073
- x: "Apple announces $110 billion stock buyback, stock surges moderately in after-hours trading"
  y: 0.07
- x: "Apple reports a sharp year-over-year drop in iPhone sales but beats earnings expectations"
  y: 0.068
- x: "Apple's Q2 2024 revenue increases moderately, but services revenue hits record high"
  y: 0.067
- x: "Apple raises quarterly dividend moderately to 25 cents per share"
  y: 0.065
- x: "Apple’s China revenue drops year-over-year, stock remains resilient"
  y: 0.012
- x: "Apple stock rallies moderately after record Q1 2025 earnings report"
  y: 0.04
- x: "Apple stock slides slightly despite record iPhone sales, earnings not enough for analysts"
  y: -0.01
- x: "Apple shares climb as company forecasts higher gross margin for next quarter"
  y: 0.025
- x: "Apple stock falls sharply year-to-date amid regulatory scrutiny and iPhone slump"
  y: -0.10
- x: "Apple stock rebounds slightly year-over-year despite weak iPhone sales"
  y: 0.025
- x: "Apple buys back $14 billion of its stock after Q1 results, shares recover sharply from drop"
  y: 0.08
- x: "Apple’s services revenue rises slightly year-over-year, offsetting hardware decline"
  y: 0.02
- x: "Apple unveils new iPad Pro, stock rises slightly after event announcement"
  y: 0.024
- x: "Apple’s active devices reach all-time high, company declares cash dividend"
  y: 0.018
- x: "Apple’s stock surges on Wall Street optimism after AI-focused announcements"
  y: 0.07